# Generated by Django 5.2.6 on 2025-09-23 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.IntegerField(db_column='id_cliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tbl_Clientes',
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.IntegerField(db_column='codigo_perfil', primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Perfiles_Empleados',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.IntegerField(db_column='codigo_provedor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Tbl_Provedores',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.IntegerField(db_column='codigo_servicio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Tbl_Servicios',
            },
        ),
        migrations.CreateModel(
            name='StockJoya',
            fields=[
                ('id', models.IntegerField(db_column='codigo_joya', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.BinaryField(blank=True, max_length='max', null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Tbl_Stock_Joyas',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.IntegerField(db_column='id_empleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('perfil', models.ForeignKey(db_column='codigo_perfil', on_delete=django.db.models.deletion.PROTECT, to='api.perfilempleado')),
            ],
            options={
                'db_table': 'Tbl_Empleados',
            },
        ),
        migrations.CreateModel(
            name='StockInsumo',
            fields=[
                ('id', models.IntegerField(db_column='codigo_insumo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_insumo', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_existencia', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('proveedor', models.ForeignKey(db_column='codigo_provedor', on_delete=django.db.models.deletion.PROTECT, to='api.proveedor')),
            ],
            options={
                'db_table': 'Tbl_StockInsumos',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.IntegerField(db_column='codigo_venta', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('isv', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estado_pago', models.IntegerField(blank=True, null=True)),
                ('abono', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='api.cliente')),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, to='api.empleado')),
            ],
            options={
                'db_table': 'Tbl_Ventas',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.IntegerField(db_column='codigo_orden', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('costo_mano_de_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estado_orden', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.PROTECT, to='api.empleado')),
                ('venta', models.ForeignKey(blank=True, db_column='codigo_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.venta')),
            ],
            options={
                'db_table': 'Tbl_Ordenes',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.IntegerField(db_column='codigo_detalle_venta', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('servicio', models.ForeignKey(blank=True, db_column='codigo_servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicio')),
                ('joya', models.ForeignKey(blank=True, db_column='codigo_joya', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stockjoya')),
                ('venta', models.ForeignKey(db_column='codigo_venta', on_delete=django.db.models.deletion.CASCADE, to='api.venta')),
            ],
            options={
                'db_table': 'Tbl_Detalles_Ventas',
            },
        ),
        migrations.CreateModel(
            name='InsumoXOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.ForeignKey(db_column='codigo_orden', on_delete=django.db.models.deletion.CASCADE, to='api.orden')),
                ('insumo', models.ForeignKey(db_column='codigo_insumo', on_delete=django.db.models.deletion.PROTECT, to='api.stockinsumo')),
            ],
            options={
                'db_table': 'Tbl_Insumos_x_Orden',
                'unique_together': {('orden', 'insumo')},
            },
        ),
    ]
